doberman.version = 0
doberman.name = "examples_cel"

[printf.h1c]
    url.cel = "printf('http://127.0.0.1:8080/%s0000000000', char(count.index % uint(26) + uint(97)))"
    [printf.h1c.headers]
    Host = "localhost"
    Connection = "close"
    [printf.run]
    count.cel = "26 * 5"
