doberman.version = 0
doberman.name = "implicit_defaults"

[[doberman.defaults]]
selector = ["graphql", "graphql_h1c", "graphql_h1", "graphql_h2", "graphql_h2c", "graphql_h3"]
    [doberman.defaults.http]
    url.cel = "current.graphql.plan.url"
    method = "POST"
    headers.Content-Type = "application/json"
    headers.Host.cel = "current.graphql.plan.url.parse_url().host"
    [doberman.defaults.h1c]
    url.cel = "current.graphql.plan.url"
    method = "POST"
    headers.Content-Type = "application/json"
    headers.Host.cel = "current.graphql.plan.url.parse_url().host"
    [doberman.defaults.h1]
    url.cel = "current.graphql.plan.url"
    method = "POST"
    headers.Content-Type = "application/json"
    headers.Host.cel = "current.graphql.plan.url.parse_url().host"
    [doberman.defaults.h2c]
    url.cel = "current.graphql.plan.url"
    method = "POST"
    headers.Content-Type = "application/json"
    headers.Host.cel = "current.graphql.plan.url.parse_url().host"
    [doberman.defaults.h2]
    url.cel = "current.graphql.plan.url"
    method = "POST"
    headers.Content-Type = "application/json"
    headers.Host.cel = "current.graphql.plan.url.parse_url().host"
    [doberman.defaults.h3]
    url.cel = "current.graphql.plan.url"
    method = "POST"
    body.cel = "current.graphql.plan.body.to_json()"
    headers.Content-Type = "application/json"
    headers.Content-Length.cel = "current.graphql.plan.body.to_json().len()"
    headers.Host.cel = "current.graphql.plan.url.parse_url().host"

[[doberman.defaults]]
selector = ["h1c", "graphql_h1c"]
    [doberman.defaults.tcp]
    host.cel = "current.h1c.plan.url.parse_url().host"
    port.cel = "current.h1c.plan.url.parse_url().port_or_default"

[[doberman.defaults]]
selector = ["h1", "graphql_h1"]
    [doberman.defaults.tls]
    host.cel = "current.h1.plan.url.parse_url().host"
    port.cel = "current.h1.plan.url.parse_url().port_or_default"

[[doberman.defaults]]
selector = ["h2c", "graphql_h2c"]
    [doberman.defaults.raw_h2c]
    host.cel = "current.h2c.plan.url.parse_url().host"
    port.cel = "current.h2c.plan.url.parse_url().port_or_default"

[[doberman.defaults]]
selector = ["raw_h2c", "h2c", "graphql_h2c"]
    [doberman.defaults.tcp]
    host.cel = "current.raw_h2c.plan.host"
    port.cel = "current.raw_h2c.plan.port"

[[doberman.defaults]]
selector = ["h2", "graphql_h2"]
    [doberman.defaults.raw_h2]
    host.cel = "current.h2.plan.url.parse_url().host"
    port.cel = "current.h2.plan.url.parse_url().port_or_default"

[[doberman.defaults]]
selector = ["raw_h2", "h2", "graphql_h2"]
    [doberman.defaults.tls]
    host.cel = "current.raw_h2.plan.host"
    port.cel = "current.raw_h2.plan.port"
    alpn = "h2"

[[doberman.defaults]]
selector = ["tls", "h1", "raw_h2", "h2", "graphql_h1", "graphql_h2"]
    [doberman.defaults.tcp]
    host.cel = "current.tls.plan.host"
    port.cel = "current.tls.plan.port"

[[doberman.defaults]]
selector = ["tcp", "tls", "h1", "h1c", "raw_h2", "h2", "raw_h2c", "h2c", "graphql_h1", "graphql_h1c", "graphql_h2", "graphql_h2c"]
    [doberman.defaults.raw_tcp]
    dest_host.cel = "current.tcp.plan.host"
    dest_port.cel = "current.tcp.plan.port"

[[doberman.defaults]]
selector = ["dtls"]
    [doberman.defaults.udp]
    host.cel = "current.dtls.plan.host"
    port.cel = "current.dtls.plan.port"

[[doberman.defaults]]
    http.method = "GET"
    http.add_content_length = "auto"
    h1c.method = "GET"
    h1c.add_content_length = "auto"
    h1c.version_string = "HTTP/1.1"
    h1.method = "GET"
    h1.add_content_length = "auto"
    h1.version_string = "HTTP/1.1"
    h2c.method = "GET"
    h2c.add_content_length = "auto"
    h2.method = "GET"
    h2.add_content_length = "auto"
    tcp.close.timeout = "30s"

